// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/onkernel/hypeman/cmd/api/api"
	"github.com/onkernel/hypeman/cmd/api/config"
	"github.com/onkernel/hypeman/lib/images"
	"github.com/onkernel/hypeman/lib/instances"
	"github.com/onkernel/hypeman/lib/providers"
	"github.com/onkernel/hypeman/lib/volumes"
	"log/slog"
)

import (
	_ "embed"
)

// Injectors from wire.go:

// initializeApp is the injector function
func initializeApp() (*application, func(), error) {
	logger := providers.ProvideLogger()
	context := providers.ProvideContext(logger)
	config := providers.ProvideConfig()
	manager := providers.ProvideImageManager(config)
	instancesManager := providers.ProvideInstanceManager(config)
	volumesManager := providers.ProvideVolumeManager(config)
	apiService := api.New(config, manager, instancesManager, volumesManager)
	mainApplication := &application{
		Ctx:             context,
		Logger:          logger,
		Config:          config,
		ImageManager:    manager,
		InstanceManager: instancesManager,
		VolumeManager:   volumesManager,
		ApiService:      apiService,
	}
	return mainApplication, func() {
	}, nil
}

// wire.go:

// application struct to hold initialized components
type application struct {
	Ctx             context.Context
	Logger          *slog.Logger
	Config          *config.Config
	ImageManager    images.Manager
	InstanceManager instances.Manager
	VolumeManager   volumes.Manager
	ApiService      *api.ApiService
}
