// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/guest/guest.proto

package guest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ExecRequest represents messages from client to server
type ExecRequest struct {
	// Types that are valid to be assigned to Request:
	//
	//	*ExecRequest_Start
	//	*ExecRequest_Stdin
	Request              isExecRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExecRequest) Reset()         { *m = ExecRequest{} }
func (m *ExecRequest) String() string { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()    {}
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{0}
}

func (m *ExecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecRequest.Unmarshal(m, b)
}
func (m *ExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecRequest.Marshal(b, m, deterministic)
}
func (m *ExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecRequest.Merge(m, src)
}
func (m *ExecRequest) XXX_Size() int {
	return xxx_messageInfo_ExecRequest.Size(m)
}
func (m *ExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecRequest proto.InternalMessageInfo

type isExecRequest_Request interface {
	isExecRequest_Request()
}

type ExecRequest_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

func (*ExecRequest_Start) isExecRequest_Request() {}

func (*ExecRequest_Stdin) isExecRequest_Request() {}

func (m *ExecRequest) GetRequest() isExecRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ExecRequest) GetStart() *ExecStart {
	if x, ok := m.GetRequest().(*ExecRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (m *ExecRequest) GetStdin() []byte {
	if x, ok := m.GetRequest().(*ExecRequest_Stdin); ok {
		return x.Stdin
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExecRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExecRequest_Start)(nil),
		(*ExecRequest_Stdin)(nil),
	}
}

// ExecStart initiates command execution
type ExecStart struct {
	Command              []string          `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Tty                  bool              `protobuf:"varint,2,opt,name=tty,proto3" json:"tty,omitempty"`
	Env                  map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cwd                  string            `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	TimeoutSeconds       int32             `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExecStart) Reset()         { *m = ExecStart{} }
func (m *ExecStart) String() string { return proto.CompactTextString(m) }
func (*ExecStart) ProtoMessage()    {}
func (*ExecStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{1}
}

func (m *ExecStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecStart.Unmarshal(m, b)
}
func (m *ExecStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecStart.Marshal(b, m, deterministic)
}
func (m *ExecStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecStart.Merge(m, src)
}
func (m *ExecStart) XXX_Size() int {
	return xxx_messageInfo_ExecStart.Size(m)
}
func (m *ExecStart) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecStart.DiscardUnknown(m)
}

var xxx_messageInfo_ExecStart proto.InternalMessageInfo

func (m *ExecStart) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ExecStart) GetTty() bool {
	if m != nil {
		return m.Tty
	}
	return false
}

func (m *ExecStart) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ExecStart) GetCwd() string {
	if m != nil {
		return m.Cwd
	}
	return ""
}

func (m *ExecStart) GetTimeoutSeconds() int32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

// ExecResponse represents messages from server to client
type ExecResponse struct {
	// Types that are valid to be assigned to Response:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	//	*ExecResponse_ExitCode
	Response             isExecResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{2}
}

func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResponse.Unmarshal(m, b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
}
func (m *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(m, src)
}
func (m *ExecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecResponse.Size(m)
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

type isExecResponse_Response interface {
	isExecResponse_Response()
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*ExecResponse_Stdout) isExecResponse_Response() {}

func (*ExecResponse_Stderr) isExecResponse_Response() {}

func (*ExecResponse_ExitCode) isExecResponse_Response() {}

func (m *ExecResponse) GetResponse() isExecResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ExecResponse) GetStdout() []byte {
	if x, ok := m.GetResponse().(*ExecResponse_Stdout); ok {
		return x.Stdout
	}
	return nil
}

func (m *ExecResponse) GetStderr() []byte {
	if x, ok := m.GetResponse().(*ExecResponse_Stderr); ok {
		return x.Stderr
	}
	return nil
}

func (m *ExecResponse) GetExitCode() int32 {
	if x, ok := m.GetResponse().(*ExecResponse_ExitCode); ok {
		return x.ExitCode
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExecResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
		(*ExecResponse_ExitCode)(nil),
	}
}

// CopyToGuestRequest represents messages for copying files to guest
type CopyToGuestRequest struct {
	// Types that are valid to be assigned to Request:
	//
	//	*CopyToGuestRequest_Start
	//	*CopyToGuestRequest_Data
	//	*CopyToGuestRequest_End
	Request              isCopyToGuestRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CopyToGuestRequest) Reset()         { *m = CopyToGuestRequest{} }
func (m *CopyToGuestRequest) String() string { return proto.CompactTextString(m) }
func (*CopyToGuestRequest) ProtoMessage()    {}
func (*CopyToGuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{3}
}

func (m *CopyToGuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyToGuestRequest.Unmarshal(m, b)
}
func (m *CopyToGuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyToGuestRequest.Marshal(b, m, deterministic)
}
func (m *CopyToGuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyToGuestRequest.Merge(m, src)
}
func (m *CopyToGuestRequest) XXX_Size() int {
	return xxx_messageInfo_CopyToGuestRequest.Size(m)
}
func (m *CopyToGuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyToGuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyToGuestRequest proto.InternalMessageInfo

type isCopyToGuestRequest_Request interface {
	isCopyToGuestRequest_Request()
}

type CopyToGuestRequest_Start struct {
	Start *CopyToGuestStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type CopyToGuestRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type CopyToGuestRequest_End struct {
	End *CopyToGuestEnd `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*CopyToGuestRequest_Start) isCopyToGuestRequest_Request() {}

func (*CopyToGuestRequest_Data) isCopyToGuestRequest_Request() {}

func (*CopyToGuestRequest_End) isCopyToGuestRequest_Request() {}

func (m *CopyToGuestRequest) GetRequest() isCopyToGuestRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CopyToGuestRequest) GetStart() *CopyToGuestStart {
	if x, ok := m.GetRequest().(*CopyToGuestRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (m *CopyToGuestRequest) GetData() []byte {
	if x, ok := m.GetRequest().(*CopyToGuestRequest_Data); ok {
		return x.Data
	}
	return nil
}

func (m *CopyToGuestRequest) GetEnd() *CopyToGuestEnd {
	if x, ok := m.GetRequest().(*CopyToGuestRequest_End); ok {
		return x.End
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CopyToGuestRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CopyToGuestRequest_Start)(nil),
		(*CopyToGuestRequest_Data)(nil),
		(*CopyToGuestRequest_End)(nil),
	}
}

// CopyToGuestStart initiates a copy-to-guest operation
type CopyToGuestStart struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode                 uint32   `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir                bool     `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Mtime                int64    `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Uid                  uint32   `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyToGuestStart) Reset()         { *m = CopyToGuestStart{} }
func (m *CopyToGuestStart) String() string { return proto.CompactTextString(m) }
func (*CopyToGuestStart) ProtoMessage()    {}
func (*CopyToGuestStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{4}
}

func (m *CopyToGuestStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyToGuestStart.Unmarshal(m, b)
}
func (m *CopyToGuestStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyToGuestStart.Marshal(b, m, deterministic)
}
func (m *CopyToGuestStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyToGuestStart.Merge(m, src)
}
func (m *CopyToGuestStart) XXX_Size() int {
	return xxx_messageInfo_CopyToGuestStart.Size(m)
}
func (m *CopyToGuestStart) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyToGuestStart.DiscardUnknown(m)
}

var xxx_messageInfo_CopyToGuestStart proto.InternalMessageInfo

func (m *CopyToGuestStart) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CopyToGuestStart) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *CopyToGuestStart) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *CopyToGuestStart) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CopyToGuestStart) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *CopyToGuestStart) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CopyToGuestStart) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

// CopyToGuestEnd signals the end of a file transfer
type CopyToGuestEnd struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyToGuestEnd) Reset()         { *m = CopyToGuestEnd{} }
func (m *CopyToGuestEnd) String() string { return proto.CompactTextString(m) }
func (*CopyToGuestEnd) ProtoMessage()    {}
func (*CopyToGuestEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{5}
}

func (m *CopyToGuestEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyToGuestEnd.Unmarshal(m, b)
}
func (m *CopyToGuestEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyToGuestEnd.Marshal(b, m, deterministic)
}
func (m *CopyToGuestEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyToGuestEnd.Merge(m, src)
}
func (m *CopyToGuestEnd) XXX_Size() int {
	return xxx_messageInfo_CopyToGuestEnd.Size(m)
}
func (m *CopyToGuestEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyToGuestEnd.DiscardUnknown(m)
}

var xxx_messageInfo_CopyToGuestEnd proto.InternalMessageInfo

// CopyToGuestResponse is the response after a copy-to-guest operation
type CopyToGuestResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	BytesWritten         int64    `protobuf:"varint,3,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyToGuestResponse) Reset()         { *m = CopyToGuestResponse{} }
func (m *CopyToGuestResponse) String() string { return proto.CompactTextString(m) }
func (*CopyToGuestResponse) ProtoMessage()    {}
func (*CopyToGuestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{6}
}

func (m *CopyToGuestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyToGuestResponse.Unmarshal(m, b)
}
func (m *CopyToGuestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyToGuestResponse.Marshal(b, m, deterministic)
}
func (m *CopyToGuestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyToGuestResponse.Merge(m, src)
}
func (m *CopyToGuestResponse) XXX_Size() int {
	return xxx_messageInfo_CopyToGuestResponse.Size(m)
}
func (m *CopyToGuestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyToGuestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyToGuestResponse proto.InternalMessageInfo

func (m *CopyToGuestResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CopyToGuestResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CopyToGuestResponse) GetBytesWritten() int64 {
	if m != nil {
		return m.BytesWritten
	}
	return 0
}

// CopyFromGuestRequest initiates a copy-from-guest operation
type CopyFromGuestRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FollowLinks          bool     `protobuf:"varint,2,opt,name=follow_links,json=followLinks,proto3" json:"follow_links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromGuestRequest) Reset()         { *m = CopyFromGuestRequest{} }
func (m *CopyFromGuestRequest) String() string { return proto.CompactTextString(m) }
func (*CopyFromGuestRequest) ProtoMessage()    {}
func (*CopyFromGuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{7}
}

func (m *CopyFromGuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromGuestRequest.Unmarshal(m, b)
}
func (m *CopyFromGuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromGuestRequest.Marshal(b, m, deterministic)
}
func (m *CopyFromGuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromGuestRequest.Merge(m, src)
}
func (m *CopyFromGuestRequest) XXX_Size() int {
	return xxx_messageInfo_CopyFromGuestRequest.Size(m)
}
func (m *CopyFromGuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromGuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromGuestRequest proto.InternalMessageInfo

func (m *CopyFromGuestRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CopyFromGuestRequest) GetFollowLinks() bool {
	if m != nil {
		return m.FollowLinks
	}
	return false
}

// CopyFromGuestResponse streams file data from guest
type CopyFromGuestResponse struct {
	// Types that are valid to be assigned to Response:
	//
	//	*CopyFromGuestResponse_Header
	//	*CopyFromGuestResponse_Data
	//	*CopyFromGuestResponse_End
	//	*CopyFromGuestResponse_Error
	Response             isCopyFromGuestResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *CopyFromGuestResponse) Reset()         { *m = CopyFromGuestResponse{} }
func (m *CopyFromGuestResponse) String() string { return proto.CompactTextString(m) }
func (*CopyFromGuestResponse) ProtoMessage()    {}
func (*CopyFromGuestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{8}
}

func (m *CopyFromGuestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromGuestResponse.Unmarshal(m, b)
}
func (m *CopyFromGuestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromGuestResponse.Marshal(b, m, deterministic)
}
func (m *CopyFromGuestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromGuestResponse.Merge(m, src)
}
func (m *CopyFromGuestResponse) XXX_Size() int {
	return xxx_messageInfo_CopyFromGuestResponse.Size(m)
}
func (m *CopyFromGuestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromGuestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromGuestResponse proto.InternalMessageInfo

type isCopyFromGuestResponse_Response interface {
	isCopyFromGuestResponse_Response()
}

type CopyFromGuestResponse_Header struct {
	Header *CopyFromGuestHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type CopyFromGuestResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type CopyFromGuestResponse_End struct {
	End *CopyFromGuestEnd `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

type CopyFromGuestResponse_Error struct {
	Error *CopyFromGuestError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*CopyFromGuestResponse_Header) isCopyFromGuestResponse_Response() {}

func (*CopyFromGuestResponse_Data) isCopyFromGuestResponse_Response() {}

func (*CopyFromGuestResponse_End) isCopyFromGuestResponse_Response() {}

func (*CopyFromGuestResponse_Error) isCopyFromGuestResponse_Response() {}

func (m *CopyFromGuestResponse) GetResponse() isCopyFromGuestResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *CopyFromGuestResponse) GetHeader() *CopyFromGuestHeader {
	if x, ok := m.GetResponse().(*CopyFromGuestResponse_Header); ok {
		return x.Header
	}
	return nil
}

func (m *CopyFromGuestResponse) GetData() []byte {
	if x, ok := m.GetResponse().(*CopyFromGuestResponse_Data); ok {
		return x.Data
	}
	return nil
}

func (m *CopyFromGuestResponse) GetEnd() *CopyFromGuestEnd {
	if x, ok := m.GetResponse().(*CopyFromGuestResponse_End); ok {
		return x.End
	}
	return nil
}

func (m *CopyFromGuestResponse) GetError() *CopyFromGuestError {
	if x, ok := m.GetResponse().(*CopyFromGuestResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CopyFromGuestResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CopyFromGuestResponse_Header)(nil),
		(*CopyFromGuestResponse_Data)(nil),
		(*CopyFromGuestResponse_End)(nil),
		(*CopyFromGuestResponse_Error)(nil),
	}
}

// CopyFromGuestHeader provides metadata about a file being copied
type CopyFromGuestHeader struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode                 uint32   `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir                bool     `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	IsSymlink            bool     `protobuf:"varint,4,opt,name=is_symlink,json=isSymlink,proto3" json:"is_symlink,omitempty"`
	LinkTarget           string   `protobuf:"bytes,5,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"`
	Size                 int64    `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Mtime                int64    `protobuf:"varint,7,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Uid                  uint32   `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,9,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromGuestHeader) Reset()         { *m = CopyFromGuestHeader{} }
func (m *CopyFromGuestHeader) String() string { return proto.CompactTextString(m) }
func (*CopyFromGuestHeader) ProtoMessage()    {}
func (*CopyFromGuestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{9}
}

func (m *CopyFromGuestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromGuestHeader.Unmarshal(m, b)
}
func (m *CopyFromGuestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromGuestHeader.Marshal(b, m, deterministic)
}
func (m *CopyFromGuestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromGuestHeader.Merge(m, src)
}
func (m *CopyFromGuestHeader) XXX_Size() int {
	return xxx_messageInfo_CopyFromGuestHeader.Size(m)
}
func (m *CopyFromGuestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromGuestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromGuestHeader proto.InternalMessageInfo

func (m *CopyFromGuestHeader) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CopyFromGuestHeader) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *CopyFromGuestHeader) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *CopyFromGuestHeader) GetIsSymlink() bool {
	if m != nil {
		return m.IsSymlink
	}
	return false
}

func (m *CopyFromGuestHeader) GetLinkTarget() string {
	if m != nil {
		return m.LinkTarget
	}
	return ""
}

func (m *CopyFromGuestHeader) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CopyFromGuestHeader) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *CopyFromGuestHeader) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CopyFromGuestHeader) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

// CopyFromGuestEnd signals the end of a file or transfer
type CopyFromGuestEnd struct {
	Final                bool     `protobuf:"varint,1,opt,name=final,proto3" json:"final,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromGuestEnd) Reset()         { *m = CopyFromGuestEnd{} }
func (m *CopyFromGuestEnd) String() string { return proto.CompactTextString(m) }
func (*CopyFromGuestEnd) ProtoMessage()    {}
func (*CopyFromGuestEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{10}
}

func (m *CopyFromGuestEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromGuestEnd.Unmarshal(m, b)
}
func (m *CopyFromGuestEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromGuestEnd.Marshal(b, m, deterministic)
}
func (m *CopyFromGuestEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromGuestEnd.Merge(m, src)
}
func (m *CopyFromGuestEnd) XXX_Size() int {
	return xxx_messageInfo_CopyFromGuestEnd.Size(m)
}
func (m *CopyFromGuestEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromGuestEnd.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromGuestEnd proto.InternalMessageInfo

func (m *CopyFromGuestEnd) GetFinal() bool {
	if m != nil {
		return m.Final
	}
	return false
}

// CopyFromGuestError reports an error during copy
type CopyFromGuestError struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromGuestError) Reset()         { *m = CopyFromGuestError{} }
func (m *CopyFromGuestError) String() string { return proto.CompactTextString(m) }
func (*CopyFromGuestError) ProtoMessage()    {}
func (*CopyFromGuestError) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{11}
}

func (m *CopyFromGuestError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromGuestError.Unmarshal(m, b)
}
func (m *CopyFromGuestError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromGuestError.Marshal(b, m, deterministic)
}
func (m *CopyFromGuestError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromGuestError.Merge(m, src)
}
func (m *CopyFromGuestError) XXX_Size() int {
	return xxx_messageInfo_CopyFromGuestError.Size(m)
}
func (m *CopyFromGuestError) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromGuestError.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromGuestError proto.InternalMessageInfo

func (m *CopyFromGuestError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CopyFromGuestError) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// StatPathRequest requests information about a path
type StatPathRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FollowLinks          bool     `protobuf:"varint,2,opt,name=follow_links,json=followLinks,proto3" json:"follow_links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatPathRequest) Reset()         { *m = StatPathRequest{} }
func (m *StatPathRequest) String() string { return proto.CompactTextString(m) }
func (*StatPathRequest) ProtoMessage()    {}
func (*StatPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{12}
}

func (m *StatPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatPathRequest.Unmarshal(m, b)
}
func (m *StatPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatPathRequest.Marshal(b, m, deterministic)
}
func (m *StatPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatPathRequest.Merge(m, src)
}
func (m *StatPathRequest) XXX_Size() int {
	return xxx_messageInfo_StatPathRequest.Size(m)
}
func (m *StatPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatPathRequest proto.InternalMessageInfo

func (m *StatPathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *StatPathRequest) GetFollowLinks() bool {
	if m != nil {
		return m.FollowLinks
	}
	return false
}

// StatPathResponse contains information about a path
type StatPathResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	IsDir                bool     `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	IsFile               bool     `protobuf:"varint,3,opt,name=is_file,json=isFile,proto3" json:"is_file,omitempty"`
	IsSymlink            bool     `protobuf:"varint,4,opt,name=is_symlink,json=isSymlink,proto3" json:"is_symlink,omitempty"`
	LinkTarget           string   `protobuf:"bytes,5,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"`
	Mode                 uint32   `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Size                 int64    `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Error                string   `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatPathResponse) Reset()         { *m = StatPathResponse{} }
func (m *StatPathResponse) String() string { return proto.CompactTextString(m) }
func (*StatPathResponse) ProtoMessage()    {}
func (*StatPathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44c1cba55f3bcb29, []int{13}
}

func (m *StatPathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatPathResponse.Unmarshal(m, b)
}
func (m *StatPathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatPathResponse.Marshal(b, m, deterministic)
}
func (m *StatPathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatPathResponse.Merge(m, src)
}
func (m *StatPathResponse) XXX_Size() int {
	return xxx_messageInfo_StatPathResponse.Size(m)
}
func (m *StatPathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatPathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatPathResponse proto.InternalMessageInfo

func (m *StatPathResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *StatPathResponse) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *StatPathResponse) GetIsFile() bool {
	if m != nil {
		return m.IsFile
	}
	return false
}

func (m *StatPathResponse) GetIsSymlink() bool {
	if m != nil {
		return m.IsSymlink
	}
	return false
}

func (m *StatPathResponse) GetLinkTarget() string {
	if m != nil {
		return m.LinkTarget
	}
	return ""
}

func (m *StatPathResponse) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *StatPathResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StatPathResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*ExecRequest)(nil), "guest.ExecRequest")
	proto.RegisterType((*ExecStart)(nil), "guest.ExecStart")
	proto.RegisterMapType((map[string]string)(nil), "guest.ExecStart.EnvEntry")
	proto.RegisterType((*ExecResponse)(nil), "guest.ExecResponse")
	proto.RegisterType((*CopyToGuestRequest)(nil), "guest.CopyToGuestRequest")
	proto.RegisterType((*CopyToGuestStart)(nil), "guest.CopyToGuestStart")
	proto.RegisterType((*CopyToGuestEnd)(nil), "guest.CopyToGuestEnd")
	proto.RegisterType((*CopyToGuestResponse)(nil), "guest.CopyToGuestResponse")
	proto.RegisterType((*CopyFromGuestRequest)(nil), "guest.CopyFromGuestRequest")
	proto.RegisterType((*CopyFromGuestResponse)(nil), "guest.CopyFromGuestResponse")
	proto.RegisterType((*CopyFromGuestHeader)(nil), "guest.CopyFromGuestHeader")
	proto.RegisterType((*CopyFromGuestEnd)(nil), "guest.CopyFromGuestEnd")
	proto.RegisterType((*CopyFromGuestError)(nil), "guest.CopyFromGuestError")
	proto.RegisterType((*StatPathRequest)(nil), "guest.StatPathRequest")
	proto.RegisterType((*StatPathResponse)(nil), "guest.StatPathResponse")
}

func init() {
	proto.RegisterFile("lib/guest/guest.proto", fileDescriptor_44c1cba55f3bcb29)
}

var fileDescriptor_44c1cba55f3bcb29 = []byte{
	// 897 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0xad, 0xe3, 0xc4, 0xb1, 0x6f, 0xd2, 0xdd, 0x68, 0xb6, 0x1f, 0x6e, 0x60, 0x45, 0x30, 0x42,
	0x6b, 0xb4, 0x52, 0xb3, 0x74, 0x11, 0x42, 0xf0, 0xd6, 0xa5, 0x25, 0x0f, 0x8b, 0x84, 0xa6, 0x2b,
	0x21, 0xed, 0x4b, 0xe4, 0xda, 0xd3, 0x64, 0xa8, 0x3f, 0xc2, 0xcc, 0xa4, 0x6d, 0xf8, 0x17, 0xbc,
	0xf0, 0xca, 0x4f, 0xe2, 0x11, 0x9e, 0xf9, 0x25, 0xe8, 0xce, 0xd8, 0xa9, 0x9d, 0x86, 0xa7, 0xee,
	0x4b, 0x3b, 0xf7, 0xf8, 0xfa, 0xcc, 0xf5, 0x39, 0x67, 0x1c, 0xc3, 0x7e, 0xca, 0x2f, 0xc7, 0xb3,
	0x25, 0x93, 0xca, 0xfc, 0x3d, 0x5e, 0x88, 0x42, 0x15, 0xa4, 0xa3, 0x8b, 0xe0, 0x3d, 0xf4, 0xce,
	0xee, 0x58, 0x4c, 0xd9, 0xaf, 0x58, 0x92, 0x10, 0x3a, 0x52, 0x45, 0x42, 0xf9, 0xd6, 0xc8, 0x0a,
	0x7b, 0x27, 0x83, 0x63, 0x73, 0x0b, 0xb6, 0x5c, 0x20, 0x3e, 0xd9, 0xa1, 0xa6, 0x81, 0x1c, 0x60,
	0x67, 0xc2, 0x73, 0xbf, 0x35, 0xb2, 0xc2, 0xbe, 0xc1, 0x13, 0x9e, 0x9f, 0x7a, 0xd0, 0x15, 0x86,
	0x2c, 0xf8, 0xdb, 0x02, 0x6f, 0x7d, 0x27, 0xf1, 0xa1, 0x1b, 0x17, 0x59, 0x16, 0xe5, 0x89, 0x6f,
	0x8d, 0xec, 0xd0, 0xa3, 0x55, 0x49, 0x06, 0x60, 0x2b, 0xb5, 0xd2, 0x44, 0x2e, 0xc5, 0x25, 0x79,
	0x09, 0x36, 0xcb, 0x6f, 0x7c, 0x7b, 0x64, 0x87, 0xbd, 0x93, 0xa3, 0xcd, 0x21, 0x8e, 0xcf, 0xf2,
	0x9b, 0xb3, 0x5c, 0x89, 0x15, 0xc5, 0x2e, 0xbc, 0x3d, 0xbe, 0x4d, 0xfc, 0xf6, 0xc8, 0x0a, 0x3d,
	0x8a, 0x4b, 0xf2, 0x02, 0x9e, 0x2a, 0x9e, 0xb1, 0x62, 0xa9, 0xa6, 0x92, 0xc5, 0x45, 0x9e, 0x48,
	0xbf, 0x33, 0xb2, 0xc2, 0x0e, 0x7d, 0x52, 0xc2, 0x17, 0x06, 0x1d, 0x7e, 0x0d, 0x6e, 0xc5, 0x85,
	0x34, 0xd7, 0x6c, 0xa5, 0x1f, 0xdc, 0xa3, 0xb8, 0x24, 0x7b, 0xd0, 0xb9, 0x89, 0xd2, 0x25, 0xd3,
	0x93, 0x79, 0xd4, 0x14, 0xdf, 0xb6, 0xbe, 0xb1, 0x82, 0x0c, 0xfa, 0x46, 0x35, 0xb9, 0x28, 0x72,
	0xc9, 0x88, 0x0f, 0x8e, 0x54, 0x49, 0xb1, 0x34, 0xba, 0xa1, 0x1a, 0x65, 0x5d, 0x5e, 0x61, 0x42,
	0xac, 0x75, 0x2a, 0x6b, 0xf2, 0x1c, 0x3c, 0x76, 0xc7, 0xd5, 0x34, 0x2e, 0x12, 0xe6, 0xdb, 0x38,
	0xde, 0x64, 0x87, 0xba, 0x08, 0xbd, 0x29, 0x12, 0x76, 0x0a, 0xe0, 0x8a, 0x92, 0x3e, 0xf8, 0xdd,
	0x02, 0xf2, 0xa6, 0x58, 0xac, 0xde, 0x15, 0x3f, 0xa0, 0x12, 0x95, 0x59, 0xe3, 0xa6, 0x59, 0x87,
	0xa5, 0x4e, 0xb5, 0xce, 0x0d, 0xcf, 0xf6, 0xa0, 0x9d, 0x44, 0x2a, 0x5a, 0x8f, 0xa2, 0x2b, 0xf2,
	0x05, 0x8a, 0x9d, 0xe8, 0x11, 0x7a, 0x27, 0xfb, 0x0f, 0x49, 0xce, 0xf2, 0x64, 0xb2, 0x83, 0x52,
	0x27, 0x75, 0x73, 0xff, 0xb4, 0x60, 0xb0, 0xb9, 0x13, 0x21, 0xd0, 0x5e, 0x44, 0x6a, 0x5e, 0x8a,
	0xa8, 0xd7, 0x88, 0x65, 0xf8, 0x88, 0xb8, 0xe9, 0x2e, 0xd5, 0x6b, 0xb2, 0x0f, 0x0e, 0x97, 0xd3,
	0x84, 0x0b, 0xbd, 0xab, 0x4b, 0x3b, 0x5c, 0x7e, 0xcf, 0x05, 0xb6, 0x4a, 0xfe, 0x1b, 0xd3, 0x56,
	0xda, 0x54, 0xaf, 0xd1, 0x84, 0x0c, 0x5d, 0xd3, 0x0e, 0xda, 0xd4, 0x14, 0x68, 0xd6, 0x92, 0x27,
	0xbe, 0xa3, 0x39, 0x71, 0x89, 0xc8, 0x8c, 0x27, 0x7e, 0xd7, 0x20, 0x33, 0x9e, 0x04, 0x03, 0x78,
	0xd2, 0x7c, 0x8a, 0xe0, 0x17, 0x78, 0xd6, 0x90, 0x71, 0xed, 0x5e, 0x57, 0x2e, 0xe3, 0x98, 0x49,
	0xa9, 0x07, 0x77, 0x69, 0x55, 0xe2, 0xe6, 0x4c, 0x88, 0x42, 0x54, 0x09, 0xd0, 0x05, 0xf9, 0x0c,
	0x76, 0x2f, 0x57, 0x8a, 0xc9, 0xe9, 0xad, 0xe0, 0x4a, 0xb1, 0x5c, 0x3f, 0x84, 0x4d, 0xfb, 0x1a,
	0xfc, 0xd9, 0x60, 0xc1, 0x8f, 0xb0, 0x87, 0x7b, 0x9d, 0x8b, 0x22, 0x6b, 0x98, 0xb6, 0x4d, 0xa2,
	0x4f, 0xa1, 0x7f, 0x55, 0xa4, 0x69, 0x71, 0x3b, 0x4d, 0x79, 0x7e, 0x2d, 0xcb, 0x93, 0xd0, 0x33,
	0xd8, 0x5b, 0x84, 0x82, 0xbf, 0x2c, 0xd8, 0xdf, 0xe0, 0x2b, 0xa7, 0xff, 0x0a, 0x9c, 0x39, 0x8b,
	0x12, 0x26, 0xca, 0x18, 0x0c, 0x6b, 0x0e, 0xae, 0xbb, 0x27, 0xba, 0x03, 0xd3, 0x67, 0x7a, 0xff,
	0x27, 0x0a, 0x2f, 0xeb, 0x51, 0x38, 0xdc, 0x46, 0x74, 0x1f, 0x06, 0xf2, 0x65, 0x25, 0x4e, 0x5b,
	0xb7, 0x1f, 0x6d, 0x6d, 0xc7, 0x06, 0x0c, 0xa0, 0xee, 0x6c, 0x84, 0xfa, 0x5f, 0xcb, 0xb8, 0xb1,
	0x31, 0xe3, 0x63, 0x33, 0xf4, 0x1c, 0x80, 0xcb, 0xa9, 0x5c, 0x65, 0x28, 0xa5, 0x1e, 0xcd, 0xa5,
	0x1e, 0x97, 0x17, 0x06, 0x20, 0x9f, 0x40, 0x0f, 0xff, 0x4f, 0x55, 0x24, 0x66, 0x4c, 0xe9, 0x50,
	0x79, 0x14, 0x10, 0x7a, 0xa7, 0x91, 0x75, 0x06, 0x9d, 0x6d, 0x19, 0xec, 0x6e, 0xc9, 0xa0, 0xfb,
	0x20, 0x83, 0xde, 0x7d, 0x06, 0x43, 0x73, 0x48, 0xea, 0xf2, 0x21, 0xdb, 0x15, 0xcf, 0xa3, 0xb4,
	0x0c, 0x9b, 0x29, 0x82, 0x53, 0x73, 0xc4, 0x9b, 0xca, 0x61, 0x34, 0x33, 0x26, 0x65, 0x34, 0x63,
	0xa5, 0x1e, 0x55, 0xb9, 0x96, 0xa9, 0x75, 0x2f, 0x53, 0x30, 0x81, 0xa7, 0x17, 0x2a, 0x52, 0x3f,
	0x45, 0x6a, 0xfe, 0xc8, 0xb8, 0xfd, 0x63, 0xc1, 0xe0, 0x9e, 0xaa, 0x4c, 0xda, 0x01, 0x38, 0xec,
	0x8e, 0x4b, 0x55, 0x1d, 0x93, 0xb2, 0xaa, 0x39, 0xd1, 0xaa, 0x3b, 0x71, 0x08, 0x5d, 0x2e, 0xa7,
	0x57, 0x3c, 0x65, 0xa5, 0x43, 0x0e, 0x97, 0xe7, 0x3c, 0x65, 0x1f, 0xc2, 0x22, 0x9d, 0x06, 0xa7,
	0x96, 0x86, 0xca, 0xb6, 0x6e, 0xd3, 0x36, 0x13, 0x50, 0xb7, 0x76, 0x7a, 0x4f, 0xfe, 0x68, 0x41,
	0xdf, 0xbc, 0xb2, 0x98, 0xb8, 0xe1, 0x31, 0x23, 0xaf, 0xa1, 0x8d, 0x2f, 0x73, 0x42, 0x6a, 0xbf,
	0x33, 0xa5, 0x7c, 0xc3, 0x67, 0x0d, 0xcc, 0xe8, 0x10, 0x5a, 0xaf, 0x2c, 0x72, 0x0e, 0xbd, 0xda,
	0xab, 0x84, 0x1c, 0x3d, 0x7c, 0x6d, 0x56, 0x14, 0xc3, 0x6d, 0x97, 0x2a, 0x26, 0xf2, 0x16, 0x76,
	0x1b, 0xb6, 0x93, 0x8f, 0xb6, 0x1d, 0xa3, 0x8a, 0xeb, 0xe3, 0xed, 0x17, 0x0d, 0xdb, 0x2b, 0x8b,
	0x7c, 0x07, 0x6e, 0xe5, 0x1a, 0x39, 0x28, 0x7b, 0x37, 0x12, 0x31, 0x3c, 0x7c, 0x80, 0x9b, 0xdb,
	0x4f, 0x5f, 0xbc, 0xff, 0x7c, 0xc6, 0xd5, 0x7c, 0x79, 0x79, 0x1c, 0x17, 0xd9, 0xb8, 0xc8, 0xaf,
	0x99, 0xc8, 0x59, 0x3a, 0x9e, 0xaf, 0x16, 0x2c, 0x8b, 0xf2, 0xf1, 0xfa, 0x33, 0xe2, 0xd2, 0xd1,
	0x5f, 0x10, 0xaf, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x85, 0xa3, 0x7e, 0x65, 0x5a, 0x08, 0x00,
	0x00,
}
