#!/usr/bin/env bash
set -euo pipefail

# Configuration
NUM_VMS=10
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/data"
BRIDGE="vmbr0"
SUBNET_BASE="192.168.100"
MAC_PREFIX="52:55:00:d1:55"

echo "========================================"
echo "Setting up $NUM_VMS VMs"
echo "========================================"

# Check if base images exist
if [ ! -f "$BASE_DIR/system/vmlinux" ] || [ ! -f "$BASE_DIR/system/initrd" ]; then
  echo "[ERROR] Base system images not found!"
  echo "Please run ./build-initrd.sh first to create the base images."
  exit 1
fi

if [ ! -f "$BASE_DIR/images/chromium-headful/v1/rootfs.ext4" ]; then
  echo "[ERROR] Rootfs image not found!"
  echo "Please run ./build-initrd.sh first to create the rootfs image."
  exit 1
fi

# Load metadata for environment variables
METADATA_FILE="$BASE_DIR/images/chromium-headful/v1/metadata.json"

# Create volumes directory
echo "[INFO] Creating volumes directory..."
mkdir -p "$BASE_DIR/volumes"

# Create hosts file for reference
echo "[INFO] Creating hosts file..."
cat > "$BASE_DIR/hosts" <<EOF
# VM hostnames for reference
# Add these to /etc/hosts if needed for DNS resolution
EOF

# Setup each VM
for i in $(seq 1 $NUM_VMS); do
  VM_ID="guest-$i"
  VM_DIR="$BASE_DIR/guests/$VM_ID"
  GUEST_IP="${SUBNET_BASE}.$((9 + i))"  # IPs: 192.168.100.10-19
  MAC_SUFFIX=$(printf "%02x" $i)
  MAC="${MAC_PREFIX}:${MAC_SUFFIX}"
  TAP="tap-${VM_ID}"
  
  echo ""
  echo "[INFO] Setting up VM $i ($VM_ID)..."
  echo "       IP: $GUEST_IP"
  echo "       MAC: $MAC"
  echo "       TAP: $TAP"
  
  # Create VM directory structure
  mkdir -p "$VM_DIR/logs"
  mkdir -p "$VM_DIR/snapshots"
  
  # Create overlay disk (50GB sparse, disk-based for faster restore)
  if [ ! -f "$VM_DIR/overlay.raw" ]; then
    echo "       Creating overlay disk (50GB sparse)..."
    truncate -s 50G "$VM_DIR/overlay.raw"
    mkfs.ext4 -q "$VM_DIR/overlay.raw"
  else
    echo "       Overlay disk already exists, skipping"
  fi
  
  # Generate config.sh for this VM
  echo "       Creating config disk..."
  CONFIG_DIR=$(mktemp -d)
  cat > "$CONFIG_DIR/config.sh" <<EOF
#!/bin/sh
# VM Configuration for $VM_ID
# Generated by setup-vms.sh

# Network configuration
GUEST_IP="$GUEST_IP"
GUEST_MASK="255.255.255.0"
GUEST_GW="${SUBNET_BASE}.1"
GUEST_DNS="1.1.1.1"

# Chromium environment variables
export CHROMIUM_FLAGS="--disable-dev-shm-usage --disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,ImprovedCookieControls,IsolateOrigins,LazyFrameLoading,MediaRouter,PaintHolding,PasswordManagerEnabled,PlzDedicatedWorker,site-per-process,Translate --disable-gpu --no-sandbox --no-zygote --remote-allow-origins=* --start-maximized --test-type"
export DISPLAY_NUM="1"
export ENABLE_WEBRTC="true"
export HEIGHT="768"
export WIDTH="1024"
export RUN_AS_ROOT="true"
export WITH_KERNEL_IMAGES_API="true"

# Entrypoint configuration
ENTRYPOINT="/wrapper.sh"
WORKDIR="/"
EOF
  
  # Create config disk (1MB is plenty for a small config file)
  rm -f "$VM_DIR/config.ext4" || true
  truncate -s 1M "$VM_DIR/config.ext4"
  mkfs.ext4 -q -d "$CONFIG_DIR" "$VM_DIR/config.ext4"
  rm -rf "$CONFIG_DIR"
  
  # Create TAP device if it doesn't exist
  if ! ip link show "$TAP" &>/dev/null; then
    echo "       Creating TAP device..."
    sudo ip tuntap add "$TAP" mode tap user "$(whoami)"
  else
    echo "       TAP device already exists"
  fi
  
  # Configure TAP device
  echo "       Configuring TAP device..."
  sudo ip link set "$TAP" up || true
  
  # Attach to bridge
  if ! sudo ip link show "$TAP" | grep -q "master $BRIDGE"; then
    sudo ip link set "$TAP" master "$BRIDGE"
  fi
  
  # Enable guest isolation on layer 2 (prevents guests from talking to each other on bridge)
  sudo ip link set "$TAP" type bridge_slave isolated on
  
  # Write metadata file
  cat > "$VM_DIR/config.json" <<EOF
{
  "vm_id": "$VM_ID",
  "ip": "$GUEST_IP",
  "mac": "$MAC",
  "tap": "$TAP",
  "gateway": "${SUBNET_BASE}.1",
  "created_at": "$(date -Iseconds)",
  "image": "chromium-headful/v1"
}
EOF
  
  # Add to hosts file
  echo "${GUEST_IP}  ${VM_ID} ${VM_ID}.local" >> "$BASE_DIR/hosts"
  
  echo "       VM $i setup complete!"
done

echo ""
echo "========================================"
echo "VM Setup Complete!"
echo "========================================"
echo "Created $NUM_VMS VMs with the following configuration:"
echo "  IPs: ${SUBNET_BASE}.10 - ${SUBNET_BASE}.19"
echo "  MACs: ${MAC_PREFIX}:01 - ${MAC_PREFIX}:0a"
echo "  TAPs: tap-guest-1 - tap-guest-10"
echo ""
echo "VM data stored in: $BASE_DIR/guests/"
echo "Hosts file created: $BASE_DIR/hosts"
echo ""
echo "Next step: Run ./scripts/start-all-vms.sh to boot all VMs"
echo "========================================"

